-- StudyPilot AI — Initial schema migration
-- Mirrors prisma/schema.prisma exactly. Generated by hand because this build
-- environment cannot reach binaries.prisma.sh to run `prisma migrate dev`.
-- In any environment with normal internet access, prefer:
--   npx prisma migrate dev --name init
-- This file lets the same schema be applied directly via psql in the meantime.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ───────────────────────── Enums ─────────────────────────

CREATE TYPE "Role" AS ENUM ('STUDENT', 'PARENT', 'TEACHER', 'ADMIN');
CREATE TYPE "GradeLevel" AS ENUM ('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3');
CREATE TYPE "SubjectCategory" AS ENUM ('CORE', 'SCIENCES', 'ARTS_HUMANITIES', 'COMMERCIAL', 'TRADE_VOCATIONAL');
CREATE TYPE "ExplanationMode" AS ENUM ('BEGINNER', 'STANDARD', 'ADVANCED', 'PIDGIN');
CREATE TYPE "QuestionType" AS ENUM ('MCQ', 'TRUE_FALSE', 'FILL_BLANK', 'SHORT_ANSWER', 'MATCHING');
CREATE TYPE "Difficulty" AS ENUM ('EASY', 'MEDIUM', 'HARD');
CREATE TYPE "QuizMode" AS ENUM ('PRACTICE', 'MOCK_EXAM', 'WEAK_AREAS', 'SPEED_ROUND');
CREATE TYPE "ExamBoard" AS ENUM ('WAEC', 'JAMB', 'NECO', 'NABTEB', 'GCSE', 'SAT');
CREATE TYPE "PlanItemType" AS ENUM ('LESSON', 'QUIZ', 'REVISION', 'PRACTICE', 'MOCK_EXAM', 'REVIEW');
CREATE TYPE "PackType" AS ENUM ('SUBJECT', 'EXAM', 'TOPIC');
CREATE TYPE "ResourceType" AS ENUM ('NOTES', 'FLASHCARDS', 'CHEATSHEET', 'MINDMAP', 'QUESTIONS');
CREATE TYPE "ResourceFormat" AS ENUM ('PDF', 'DOCX', 'INLINE');
CREATE TYPE "ConsentStatus" AS ENUM ('PENDING', 'APPROVED', 'EXPIRED');
CREATE TYPE "ModerationAction" AS ENUM ('AUTO_FILTERED', 'FLAGGED', 'BLOCKED', 'APPROVED', 'REMOVED');
CREATE TYPE "CacheType" AS ENUM ('TUTOR_EXPLANATION', 'STEP_LESSON', 'QUIZ_GEN', 'HOMEWORK_HINT', 'RESOURCE_GEN', 'STUDY_PLAN');

-- ───────────────────────── Core identity ─────────────────────────

CREATE TABLE "User" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" TEXT NOT NULL UNIQUE,
  "passwordHash" TEXT,
  "googleId" TEXT UNIQUE,
  "name" TEXT NOT NULL,
  "role" "Role" NOT NULL,
  "dateOfBirth" TIMESTAMP,
  "retainAnswers" BOOLEAN NOT NULL DEFAULT FALSE,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "User_role_idx" ON "User"("role");

CREATE TABLE "RefreshToken" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "tokenHash" TEXT NOT NULL UNIQUE,
  "expiresAt" TIMESTAMP NOT NULL,
  "revokedAt" TIMESTAMP,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "RefreshToken_userId_idx" ON "RefreshToken"("userId");

CREATE TABLE "ParentConsent" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "parentEmail" TEXT NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "status" "ConsentStatus" NOT NULL DEFAULT 'PENDING',
  "requestedAt" TIMESTAMP NOT NULL DEFAULT now(),
  "approvedAt" TIMESTAMP,
  "expiresAt" TIMESTAMP NOT NULL
);
CREATE INDEX "ParentConsent_studentId_idx" ON "ParentConsent"("studentId");

CREATE TABLE "ParentChildLink" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "parentId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "studentId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "linkedAt" TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE ("parentId", "studentId")
);

-- ───────────────────────── Role profiles ─────────────────────────

CREATE TABLE "StudentProfile" (
  "userId" UUID PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE,
  "gradeLevel" "GradeLevel" NOT NULL,
  "school" TEXT,
  "examBoards" "ExamBoard"[] NOT NULL DEFAULT '{}',
  "dailyStudyMinutesGoal" INTEGER NOT NULL DEFAULT 60,
  "xp" INTEGER NOT NULL DEFAULT 0,
  "streakCount" INTEGER NOT NULL DEFAULT 0,
  "lastStudyDate" TIMESTAMP,
  "defaultExplanationMode" "ExplanationMode" NOT NULL DEFAULT 'STANDARD',
  "lowBandwidthMode" BOOLEAN NOT NULL DEFAULT FALSE,
  "voiceEnabled" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "ParentProfile" (
  "userId" UUID PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE,
  "dailySummaryEmail" BOOLEAN NOT NULL DEFAULT TRUE,
  "weeklyReportEmail" BOOLEAN NOT NULL DEFAULT TRUE,
  "weakAreaAlerts" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "TeacherProfile" (
  "userId" UUID PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE,
  "school" TEXT
);

-- ───────────────────────── Classrooms ─────────────────────────

CREATE TABLE "Classroom" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "teacherId" UUID NOT NULL REFERENCES "TeacherProfile"("userId") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "joinCode" TEXT NOT NULL UNIQUE,
  "gradeLevel" "GradeLevel" NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "ClassroomMembership" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "classroomId" UUID NOT NULL REFERENCES "Classroom"("id") ON DELETE CASCADE,
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "joinedAt" TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE ("classroomId", "studentId")
);

-- ───────────────────────── Curriculum ─────────────────────────

CREATE TABLE "Subject" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL UNIQUE,
  "category" "SubjectCategory" NOT NULL,
  "levels" "GradeLevel"[] NOT NULL DEFAULT '{}',
  "topicCount" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX "Subject_category_idx" ON "Subject"("category");

CREATE TABLE "StudentSubject" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "subjectId" UUID NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,
  "addedAt" TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE ("studentId", "subjectId")
);

CREATE TABLE "Topic" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "subjectId" UUID NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "level" "GradeLevel" NOT NULL,
  "difficulty" "Difficulty" NOT NULL DEFAULT 'MEDIUM',
  "order" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX "Topic_subjectId_idx" ON "Topic"("subjectId");

CREATE TABLE "LearningGoal" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "classroomId" UUID NOT NULL REFERENCES "Classroom"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "subjectId" UUID REFERENCES "Subject"("id"),
  "targetScore" INTEGER,
  "dueDate" TIMESTAMP,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);

-- ───────────────────────── AI response cache ─────────────────────────

CREATE TABLE "AIResponseCache" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "cacheKey" TEXT NOT NULL UNIQUE,
  "type" "CacheType" NOT NULL,
  "requestJson" JSONB NOT NULL,
  "responseJson" JSONB NOT NULL,
  "modelUsed" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "expiresAt" TIMESTAMP NOT NULL
);
CREATE INDEX "AIResponseCache_type_idx" ON "AIResponseCache"("type");
CREATE INDEX "AIResponseCache_expiresAt_idx" ON "AIResponseCache"("expiresAt");

-- ───────────────────────── Quiz engine ─────────────────────────

CREATE TABLE "QuizQuestion" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "subjectId" UUID NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,
  "topicId" UUID REFERENCES "Topic"("id"),
  "type" "QuestionType" NOT NULL,
  "questionText" TEXT NOT NULL,
  "options" JSONB,
  "correctAnswer" JSONB NOT NULL,
  "explanation" TEXT NOT NULL,
  "difficulty" "Difficulty" NOT NULL DEFAULT 'MEDIUM',
  "examBoard" "ExamBoard",
  "aiGenerated" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "QuizQuestion_subjectId_idx" ON "QuizQuestion"("subjectId");
CREATE INDEX "QuizQuestion_topicId_idx" ON "QuizQuestion"("topicId");

CREATE TABLE "Quiz" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "subjectId" UUID NOT NULL REFERENCES "Subject"("id"),
  "topicId" UUID REFERENCES "Topic"("id"),
  "mode" "QuizMode" NOT NULL,
  "startedAt" TIMESTAMP NOT NULL DEFAULT now(),
  "completedAt" TIMESTAMP,
  "totalQuestions" INTEGER NOT NULL,
  "score" INTEGER,
  "xpEarned" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX "Quiz_studentId_idx" ON "Quiz"("studentId");
CREATE INDEX "Quiz_subjectId_idx" ON "Quiz"("subjectId");

CREATE TABLE "QuizAttemptAnswer" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "quizId" UUID NOT NULL REFERENCES "Quiz"("id") ON DELETE CASCADE,
  "questionId" UUID NOT NULL REFERENCES "QuizQuestion"("id"),
  "studentAnswer" JSONB NOT NULL,
  "isCorrect" BOOLEAN NOT NULL,
  "timeTakenSeconds" INTEGER,
  "answeredAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "QuizAttemptAnswer_quizId_idx" ON "QuizAttemptAnswer"("quizId");

-- ───────────────────────── Homework assistant ─────────────────────────

CREATE TABLE "HomeworkSession" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "subjectId" UUID REFERENCES "Subject"("id"),
  "questionText" TEXT NOT NULL,
  "imageUrl" TEXT,
  "hintsGiven" INTEGER NOT NULL DEFAULT 0,
  "resolved" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "HomeworkSession_studentId_idx" ON "HomeworkSession"("studentId");
CREATE INDEX "HomeworkSession_createdAt_idx" ON "HomeworkSession"("createdAt");

-- ───────────────────────── Study planner ─────────────────────────

CREATE TABLE "StudyPlanEntry" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "date" TIMESTAMP NOT NULL,
  "subjectId" UUID REFERENCES "Subject"("id"),
  "topicTitle" TEXT NOT NULL,
  "type" "PlanItemType" NOT NULL,
  "durationMinutes" INTEGER NOT NULL,
  "completed" BOOLEAN NOT NULL DEFAULT FALSE,
  "generatedByAI" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "StudyPlanEntry_studentId_date_idx" ON "StudyPlanEntry"("studentId", "date");

CREATE TABLE "ExamCountdown" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "examBoard" "ExamBoard" NOT NULL,
  "examDate" TIMESTAMP NOT NULL,
  "subjects" TEXT[] NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "ExamCountdown_studentId_idx" ON "ExamCountdown"("studentId");

-- ───────────────────────── Gamification ─────────────────────────

CREATE TABLE "Achievement" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "key" TEXT NOT NULL UNIQUE,
  "label" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "iconKey" TEXT NOT NULL
);

CREATE TABLE "StudentAchievement" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "achievementId" UUID NOT NULL REFERENCES "Achievement"("id"),
  "earnedAt" TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE ("studentId", "achievementId")
);

-- ───────────────────────── Offline packs ─────────────────────────

CREATE TABLE "OfflinePack" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "key" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "type" "PackType" NOT NULL,
  "subjectId" UUID REFERENCES "Subject"("id"),
  "examBoard" "ExamBoard",
  "sizeMB" DOUBLE PRECISION NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "StudentOfflineDownload" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "packId" UUID NOT NULL REFERENCES "OfflinePack"("id") ON DELETE CASCADE,
  "downloadedAt" TIMESTAMP NOT NULL DEFAULT now(),
  "downloadedVersion" INTEGER NOT NULL,
  "lastSyncedAt" TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE ("studentId", "packId")
);

-- ───────────────────────── Offline sync log (idempotency) ─────────────────────────

CREATE TABLE "SyncLogEntry" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL,
  "clientActionId" TEXT NOT NULL,
  "actionType" TEXT NOT NULL,
  "payload" JSONB NOT NULL,
  "appliedAt" TIMESTAMP NOT NULL DEFAULT now(),
  "success" BOOLEAN NOT NULL,
  UNIQUE ("studentId", "clientActionId")
);

-- ───────────────────────── Resource generator ─────────────────────────

CREATE TABLE "ResourceGeneration" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "studentId" UUID NOT NULL REFERENCES "StudentProfile"("userId") ON DELETE CASCADE,
  "subjectId" UUID REFERENCES "Subject"("id"),
  "topic" TEXT NOT NULL,
  "resourceType" "ResourceType" NOT NULL,
  "contentJson" JSONB NOT NULL,
  "format" "ResourceFormat" NOT NULL DEFAULT 'INLINE',
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "ResourceGeneration_studentId_idx" ON "ResourceGeneration"("studentId");

-- ───────────────────────── Notifications & moderation ─────────────────────────

CREATE TABLE "Notification" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "isRead" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "Notification_userId_isRead_idx" ON "Notification"("userId", "isRead");

CREATE TABLE "ModerationFlag" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "contentType" TEXT NOT NULL,
  "contentRef" TEXT,
  "studentId" UUID,
  "reason" TEXT NOT NULL,
  "action" "ModerationAction" NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "reviewedBy" UUID,
  "reviewedAt" TIMESTAMP
);
CREATE INDEX "ModerationFlag_action_idx" ON "ModerationFlag"("action");
